# -*- mode: snippet -*-
# name: docker-compose.yml
# key: dc
# expand-env: ((yas-indent-line 'fixed))
# --
$0version: '3'
services:
  $1:
    image: "${2:alpine}:${3:latest}"
    build: ./$4
    ports:
     - "$5:$5"
    volumes:
      - ./${6:src}:/${7:code}
